#############
# Play Area #
#############
- platform: generic_thermostat
  name: Diningroom UFH
  heater: switch.diningroom_ufh
  target_sensor: sensor.diningroom_ufh_temperature_floor  # BHT-1000 LCD Panel external sensor UFH temperature
  min_temp: 15.0
  max_temp: 25.0
  ac_mode: false
  cold_tolerance: 0.1
  hot_tolerance: 0.1
  initial_hvac_mode: "heat"
  away_temp: 16
  precision: 0.5

- platform: generic_thermostat
  name: Entrance UFH
  heater: switch.entrance_ufh
  target_sensor: sensor.entrance_ufh_temperature_floor  # BHT-1000 LCD Panel external sensor UFH temperature
  min_temp: 15.0
  max_temp: 25.0
  ac_mode: false
  cold_tolerance: 0.1
  hot_tolerance: 0.1
  initial_hvac_mode: "heat"
  away_temp: 16
  precision: 0.5

- platform: generic_thermostat
  name: Passage UFH
  heater: switch.passage_ufh
  target_sensor: sensor.passage_ufh_temperature_floor  # BHT-1000 LCD Panel external sensor UFH temperature
  min_temp: 15.0
  max_temp: 25.0
  ac_mode: false
  cold_tolerance: 0.1
  hot_tolerance: 0.1
  initial_hvac_mode: "heat"
  away_temp: 16
  precision: 0.5

#############
# Live Area #
#############

- platform: generic_thermostat
  name: Bedroom1 Heater
  heater: switch.bedroom1_heater_switch
#  target_sensor: sensor.bedroom1_heater_temperature # Sonoff TH16 AM2303onboard sensor
  target_sensor: sensor.bedroom1_sensor_temperature # Xiaomi Aqara Xiaomi temperature, humidity and pressure sensor
  min_temp: 15.0
  max_temp: 23.0
  ac_mode: false
  cold_tolerance: 0.1
  hot_tolerance: 0.1
  initial_hvac_mode: "heat"
  away_temp: 16
  precision: 0.5

- platform: generic_thermostat
  name: Bedroom2 Heater
  heater: switch.bedroom2_heater_switch
#  target_sensor: #sensor.bedroom2_heater_temperature # Sonoff TH16 AM2301 onboard sensor
  target_sensor: sensor.bedroom2_sensor_temperature # Xiaomi Aqara Xiaomi temperature, humidity and pressure sensor
  min_temp: 15.0
  max_temp: 23.0
  ac_mode: false
  cold_tolerance: 0.1
  hot_tolerance: 0.1
  initial_hvac_mode: "heat"
  away_temp: 16
  precision: 0.5

- platform: generic_thermostat
  name: Bedroom3 Heater
  heater: switch.bedroom3_heater_switch
#  target_sensor: sensor.bedroom3_heater_temperature # Sonoff TH16 AM2301 onboard sensor
  target_sensor: sensor.bedroom3_sensor_temperature # Xiaomi Aqara Xiaomi temperature, humidity and pressure sensor
  min_temp: 15.0
  max_temp: 23.0
  ac_mode: false
  cold_tolerance: 0.1
  hot_tolerance: 0.1
  initial_hvac_mode: "heat"
  away_temp: 16
  precision: 0.5

- platform: generic_thermostat
  name: Bedroom4 Heater
  heater: switch.bedroom4_heater_switch
#  target_sensor: sensor.bedroom_4_heater_temperature # Sonoff TH16 AM2301 onboard sensor
  target_sensor: sensor.bedroom4_sensor_temperature # Xiaomi Aqara Xiaomi temperature, humidity and pressure sensor
  min_temp: 15.0
  max_temp: 23.0
  ac_mode: false
  cold_tolerance: 0.1
  hot_tolerance: 0.1
  initial_hvac_mode: "heat"
  away_temp: 16
  precision: 0.5

- platform: generic_thermostat
  name: Entrance Heater
  heater: switch.entrance_heater_switch
#  target_sensor: sensor.entrance_heater_temperature # Sonoff TH16 AM2301 onboard sensor
  target_sensor: sensor.entrance_sensor_temperature # Xiaomi Aqara Xiaomi temperature, humidity and pressure sensor
#  target_sensor: sensor.entrance_ufh_temperature  # BHT-1000 LCD Panel temperature
  min_temp: 15.0
  max_temp: 23.0
  ac_mode: false
  cold_tolerance: 0.1
  hot_tolerance: 0.1
  initial_hvac_mode: "heat"
  away_temp: 16
  precision: 0.5

- platform: generic_thermostat
  name: Diningroom Heater
  heater: switch.diningroom_heater_switch
#  target_sensor: sensor.diningroom_heater_temperature # Sonoff TH16 AM2301 onboard sensor
  target_sensor: sensor.diningroom_sensor_temperature # Xiaomi Aqara Xiaomi temperature, humidity and pressure sensor
#  target_sensor: sensor.diningroom_ufh_temperature  # BHT-1000 LCD Panel temperature
  min_temp: 15.0
  max_temp: 23.0
  ac_mode: false
  cold_tolerance: 0.1
  hot_tolerance: 0.1
  initial_hvac_mode: "heat"
  away_temp: 16
  precision: 0.5

- platform: generic_thermostat
  name:  Guest Bathroom Heater
  heater: switch.guest_bathroom_heater_switch
#  target_sensor: sensor.guest_bathroom_heater_temperature # Sonoff TH16 AM2301 onboard sensor
  target_sensor: sensor.guest_bathroom_sensor_temperature
  min_temp: 15.0
  max_temp: 23.0
  ac_mode: false
  cold_tolerance: 0.1
  hot_tolerance: 0.1
  initial_hvac_mode: "heat"
  away_temp: 16
  precision: 0.5

- platform: generic_thermostat
  name: Kitchen Heater
  heater: switch.kitchen_heater_switch
#  target_sensor: sensor.kitchen_heater_temperature # Sonoff TH16 AM2301 onboard sensor
  target_sensor: sensor.kitchen_sensor_temperature # Xiaomi Aqara Xiaomi temperature, humidity and pressure sensor
  min_temp: 15.0
  max_temp: 23.0
  ac_mode: false
  cold_tolerance: 0.1
  hot_tolerance: 0.1
  initial_hvac_mode: "heat"
  away_temp: 16
  precision: 0.5

- platform: generic_thermostat
  name: Lounge Front Heater
  heater: switch.lounge_front_heater_switch
#  target_sensor: sensor.lounge_front_heater_temperature # Sonoff TH16 AM2301 onboard sensor
  target_sensor: sensor.lounge_sensor_temperature # Xiaomi Aqara Xiaomi temperature, humidity and pressure sensor
  min_temp: 15.0
  max_temp: 23.0
  ac_mode: false
  cold_tolerance: 0.1
  hot_tolerance: 0.1
  initial_hvac_mode: "heat"
  away_temp: 16
  precision: 0.5

- platform: generic_thermostat
  name: Lounge Side Heater
  heater: switch.lounge_side_heater_switch
#  target_sensor: sensor.lounge_side_heater_temperature # Sonoff TH16 AM2301 onboard sensor
  target_sensor: sensor.lounge_sensor_temperature # Xiaomi Aqara Xiaomi temperature, humidity and pressure sensor
  min_temp: 15.0
  max_temp: 23.0
  ac_mode: false
  cold_tolerance: 0.1
  hot_tolerance: 0.1
  initial_hvac_mode: "heat"
  away_temp: 16
  precision: 0.5

- platform: generic_thermostat
  name: Master Bathroom Heater
  heater: switch.master_bathroom_heater_switch
#  target_sensor: sensor.master_bathroom_heater_temperature # Sonoff TH16 AM2301 onboard sensor
  target_sensor: sensor.master_bathroom_sensor_temperature # Xiaomi Aqara Xiaomi temperature, humidity and pressure sensor
  min_temp: 15.0
  max_temp: 23.0
  ac_mode: false
  cold_tolerance: 0.1
  hot_tolerance: 0.1
  initial_hvac_mode: "heat"
  away_temp: 16
  precision: 0.5

- platform: generic_thermostat
  name: Office Front Heater
  heater: switch.office_front_heater_switch
#  target_sensor: sensor.office_front_heater_temperature # Sonoff TH16 AM2301 onboard sensor
  target_sensor: sensor.office_sensor_temperature # Xiaomi Aqara Xiaomi temperature, humidity and pressure sensor
  min_temp: 15.0
  max_temp: 23.0
  ac_mode: false
  cold_tolerance: 0.1
  hot_tolerance: 0.1
  initial_hvac_mode: "heat"
  away_temp: 16
  precision: 0.5

- platform: generic_thermostat
  name: Office Side Heater
  heater: switch.office_side_heater_switch
#  target_sensor: sensor.office_side_heater_temperature # Sonoff TH16 AM2301 onboard sensor
  target_sensor: sensor.office_sensor_temperature # Xiaomi Aqara Xiaomi temperature, humidity and pressure sensor
  min_temp: 15.0
  max_temp: 23.0
  ac_mode: false
  cold_tolerance: 0.1
  hot_tolerance: 0.1
  initial_hvac_mode: "heat"
  away_temp: 16
  precision: 0.5
