#############
# Play Area #
#############
#- platform: rflink868
#  automatic_add: True

#############
# Live Area #
#############
- platform: rflink
  devices:
    bofumotor_ef0f61_04:
      name: Office Side Blind
    bofumotor_ef0f61_03:
      name: Office Front Blind
    bofumotor_ef0f61_02:
      name: Lounge Right Blind
    bofumotor_ef0f61_01:
      name: Lounge Left Blind
    bofumotor_45f3c0_01:
      name: Bedroom1 Blind
    bofumotor_b7edc0_01:
      name: Bedroom2 Blind
    bofumotor_f71cc0_01:
      name: Bedroom3 Blind
    bofumotor_79f1c0_01:
      name: Bedroom4 Blind

#- platform: template
#  covers:
#    projector_screen:
#      friendly_name: "Projector Screen"
#      open_cover:
#        - service: mqtt.publish
#          data:
#            topic: 'cmnd/ProjectorScreen/POWER1'
#            payload: 'OFF'
#        - service: mqtt.publish
#          data:
#            topic: 'cmnd/ProjectorScreen/POWER2'
#            payload: 'ON'
#      close_cover:
#        - service: mqtt.publish
#          data:
#            topic: 'cmnd/ProjectorScreen/POWER1'
#            payload: 'ON'
#        - service: mqtt.publish
#          data:
#            topic: 'cmnd/ProjectorScreen/POWER2'
#            payload: 'OFF'
#      stop_cover:
#        - service: mqtt.publish
#          data:
#            topic: 'cmnd/ProjectorScreen/POWER1'
#            payload: 'OFF'
#        - service: mqtt.publish
#            topic: 'cmnd/ProjectorScreen/POWER2'
#          data:
#            payload: 'OFF'
